import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import kahip
import time
import pickle
import os
import subprocess
import sys
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split

# Local imports
from data_parser import get_dataset, build_parser, parse_cpp_output, save_knn_graph, load_knn_graph, get_unique_filename
from models import MLPClassifier
from graph_utils import build_kahip_graph_no_csr

def main():
    args = build_parser()
    
    # Set seeds
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # 1. Load Data
    print(f"Loading dataset from {args.dataset}...")
    X_train_np = get_dataset(args.type, args.dataset)
    n_samples, n_features = X_train_np.shape
    print(f"Data loaded: {n_samples} vectors of dimension {n_features}")

    # 2. Build or Load k-NN Graph
    dataset_name = os.path.splitext(os.path.basename(args.dataset))[0]
    
    if args.graph_method == "cpp_subprocess":
        method_str = f"cpp_{args.cpp_algo}"
    elif args.graph_method == "cpp_file":
        method_str = "cpp_file"
    else:
        method_str = "sklearn"
        
    graph_cache_path = os.path.join(os.path.dirname(__file__), "..", "cache", "graphs", f"knn_{dataset_name}_{method_str}_k{args.knn}.npy")
    
    indices = load_knn_graph(graph_cache_path)
    
    if indices is None:
        print(f"Building k-NN graph (k={args.knn}) using {args.graph_method}...")
        start_time = time.time()
        
        if args.graph_method == "sklearn":
            # We need k+1 because the first neighbor of a point in the training set is itself (dist=0)
            nbrs = NearestNeighbors(n_neighbors=args.knn + 1, algorithm='brute', metric='euclidean', n_jobs=-1)
            nbrs.fit(X_train_np)
            _, raw_indices = nbrs.kneighbors(X_train_np)
            # Remove the first column (self-loop)
            indices = raw_indices[:, 1:]
            
        elif args.graph_method == "cpp_file":
            if not args.graph_file:
                print("Error: --graph_file is required when graph_method is 'cpp_file'")
                sys.exit(1)
            # Expecting file to contain k+1 neighbors if generated by our C++ tool on train set
            # If the file was strictly generated as a graph (no self loops), adjust k accordingly.
            # Assuming standard output:
            raw_indices = parse_cpp_output(args.graph_file, n_samples, args.knn + 1)
            indices = raw_indices[:, 1:]
            
        elif args.graph_method == "cpp_subprocess":
            # Use absolute path to avoid C++ filesystem error on empty parent path
            temp_output = os.path.abspath("temp_cpp_knn_output.txt")
            
            # Request k+1 neighbors to account for self-loops
            k_req = args.knn + 1
            
            # Pass all required arguments to avoid interactive prompts from C++
            cmd = [
                args.cpp_bin,
                "-algo", args.cpp_algo,
                "-d", args.dataset,
                "-q", args.dataset,
                "-o", temp_output,
                "-type", args.type,
                "-N", str(k_req),
                "-metric", "l2",       # Explicitly set metric
                "-range", "false",     # Disable range search for graph construction
                "-R", "0.0"
            ]

            # Pass IVFFlat specific arguments if that algo is chosen
            if args.cpp_algo == "ivfflat":
                cmd.extend(["-kclusters", str(args.kclusters)])
                cmd.extend(["-nprobe", str(args.nprobe)])

            print(f"Running C++ subprocess: {' '.join(cmd)}")
            try:
                subprocess.run(cmd, check=True)
                # Parse k+1, then remove self-loops
                raw_indices = parse_cpp_output(temp_output, n_samples, k_req)
                indices = raw_indices[:, 1:] 
                
                #if os.path.exists(temp_output):
                #    os.remove(temp_output)
            except subprocess.CalledProcessError as e:
                print(f"Error running C++ executable: {e}")
                sys.exit(1)
            except FileNotFoundError:
                print(f"Error: C++ executable not found at {args.cpp_bin}")
                sys.exit(1)

        print(f"k-NN graph constructed in {time.time() - start_time:.2f}s")
        save_knn_graph(indices, graph_cache_path)

    # 3. Prepare Graph for KaHIP
    xadj, adjncy, adjcwgt, vwgt = build_kahip_graph_no_csr(indices, args.knn)

    # 4. KaHIP Partitioning
    print(f"Running KaHIP partitioning (m={args.m})...")
    start_time = time.time()
    
    # Pass arguments positionally. The kahip binding does not support keyword arguments.
    # Signature: (vwgt, xadj, adjcwgt, adjncy, k, imbalance, suppress_output, seed, mode)
    edgecut, blocks = kahip.kaffpa(
        vwgt, xadj, adjcwgt, adjncy,
        args.m,
        args.imbalance,
        True,
        args.seed,
        args.kahip_mode
    )
    
    print(f"Partitioning completed in {time.time() - start_time:.2f}s. Edge cut: {edgecut}")

    # --- PLOT: Partition Balance ---
    fig_dir = os.path.join(os.path.dirname(__file__), "fig")
    os.makedirs(fig_dir, exist_ok=True)
    
    unique, counts = np.unique(blocks, return_counts=True)
    plt.figure(figsize=(10, 6))
    plt.bar(unique, counts, color='skyblue', edgecolor='black')
    plt.xlabel('Partition ID')
    plt.ylabel('Number of Points')
    plt.title(f'KaHIP Partition Balance (m={args.m}, imbalance={args.imbalance})')
    plt.grid(axis='y', alpha=0.75)
    
    # Unique filename with params
    base_plot_name = f"partition_balance_{dataset_name}_m{args.m}_imb{args.imbalance}_mode{args.kahip_mode}_seed{args.seed}.png"
    plot_path = get_unique_filename(os.path.join(fig_dir, base_plot_name))
    
    plt.savefig(plot_path)
    plt.close()
    print(f"Saved partition balance plot to {plot_path}")
    # -------------------------------

    labels = torch.tensor(blocks, dtype=torch.long).to(device)
    X_train = torch.from_numpy(X_train_np).to(device)

    # 5. Train Classifier
    print("Training Neural Classifier...")
    
    # Split into Train and Validation sets (90% Train, 10% Val)
    indices_all = np.arange(n_samples)
    train_idx, val_idx = train_test_split(indices_all, test_size=0.1, random_state=args.seed)
    
    train_dataset = TensorDataset(X_train[train_idx], labels[train_idx])
    val_dataset = TensorDataset(X_train[val_idx], labels[val_idx])
    
    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False)

    hidden_units = [args.nodes] * (max(1, args.layers - 1))
    
    model = MLPClassifier(
        d_in=n_features, 
        n_out=args.m, 
        hidden_units=hidden_units,
        activation='relu',
        dropout=0.1
    ).to(device)
    
    optimizer = optim.Adam(model.parameters(), lr=args.lr)
    criterion = nn.CrossEntropyLoss()
    
    start_time = time.time()
    
    # Metrics storage
    history = {
        'train_loss': [], 'val_loss': [],
        'train_acc': [], 'val_acc': []
    }

    for epoch in range(args.epochs):
        # --- Training Phase ---
        model.train()
        total_loss = 0
        correct_train = 0
        total_train = 0
        
        # tqdm for batch progress
        train_pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{args.epochs}", leave=False)
        
        for batch_x, batch_y in train_pbar:
            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()
            
            total_loss += loss.item()
            
            # Accuracy
            _, predicted = torch.max(outputs.data, 1)
            total_train += batch_y.size(0)
            correct_train += (predicted == batch_y).sum().item()
            
            # Update pbar
            train_pbar.set_postfix({'loss': f'{loss.item():.4f}'})
        
        avg_train_loss = total_loss / len(train_loader)
        train_acc = correct_train / total_train
        
        # --- Validation Phase ---
        model.eval()
        val_loss = 0
        correct_val = 0
        total_val = 0
        
        with torch.no_grad():
            for batch_x, batch_y in val_loader:
                outputs = model(batch_x)
                loss = criterion(outputs, batch_y)
                val_loss += loss.item()
                
                _, predicted = torch.max(outputs.data, 1)
                total_val += batch_y.size(0)
                correct_val += (predicted == batch_y).sum().item()
        
        avg_val_loss = val_loss / len(val_loader)
        val_acc = correct_val / total_val
        
        # Store metrics
        history['train_loss'].append(avg_train_loss)
        history['val_loss'].append(avg_val_loss)
        history['train_acc'].append(train_acc)
        history['val_acc'].append(val_acc)
        
        print(f"Epoch {epoch+1}/{args.epochs} | "
              f"Train Loss: {avg_train_loss:.4f} Acc: {train_acc:.4f} | "
              f"Val Loss: {avg_val_loss:.4f} Acc: {val_acc:.4f}")
    
    print(f"Training completed in {time.time() - start_time:.2f}s")

    # --- PLOT: Learning Curves (Loss & Accuracy) ---
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))
    
    # Loss Plot
    ax1.plot(range(1, args.epochs + 1), history['train_loss'], label='Train Loss', marker='o')
    ax1.plot(range(1, args.epochs + 1), history['val_loss'], label='Val Loss', marker='x')
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Cross Entropy Loss')
    ax1.set_title(f'Loss Curve (L={args.layers}, N={args.nodes})')
    ax1.legend()
    ax1.grid(True)
    
    # Accuracy Plot
    ax2.plot(range(1, args.epochs + 1), history['train_acc'], label='Train Acc', marker='o')
    ax2.plot(range(1, args.epochs + 1), history['val_acc'], label='Val Acc', marker='x')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Accuracy')
    ax2.set_title(f'Accuracy Curve (LR={args.lr})')
    ax2.legend()
    ax2.grid(True)
    
    # Unique filename with params
    base_lc_name = f"learning_curve_{dataset_name}_L{args.layers}_N{args.nodes}_E{args.epochs}_seed{args.seed}.png"
    plot_path = get_unique_filename(os.path.join(fig_dir, base_lc_name))
    
    plt.savefig(plot_path)
    plt.close()
    print(f"Saved learning curve plot to {plot_path}")
    # ----------------------------

    # 6. Save Index
    # Ensure directory exists for index path
    index_dir = os.path.dirname(args.index)
    if index_dir:
        os.makedirs(index_dir, exist_ok=True)

    model_path = f"{args.index}_model.pth"
    torch.save({
        "model_state": model.state_dict(),
        "config": {
            "d_in": n_features,
            "n_out": args.m,
            "hidden_units": hidden_units,
            "activation": 'relu',
            "dropout": 0.1
        }
    }, model_path)
    
    inverted_file = {}
    blocks_np = np.array(blocks)
    for i in range(args.m):
        idxs = np.where(blocks_np == i)[0].tolist()
        inverted_file[i] = idxs
        
    # Calculate Bin Statistics
    bin_sizes = [len(idxs) for idxs in inverted_file.values()]
    bin_min = np.min(bin_sizes) if bin_sizes else 0
    bin_max = np.max(bin_sizes) if bin_sizes else 0
    bin_mean = np.mean(bin_sizes) if bin_sizes else 0
    bin_median = np.median(bin_sizes) if bin_sizes else 0
    non_empty_bins = sum(1 for s in bin_sizes if s > 0)
    
    print(f"\n[Index Stats] Bins: {args.m} | Non-empty: {non_empty_bins}")
    print(f"[Index Stats] Size -> Min: {bin_min}, Max: {bin_max}, Mean: {bin_mean:.1f}, Median: {bin_median}")

    index_file_path = f"{args.index}_index.pkl"
    with open(index_file_path, "wb") as f:
        pickle.dump(inverted_file, f)

    # Save Configuration Text File
    config_path = f"{args.index}_config.txt"
    with open(config_path, "w") as f:
        f.write(f"m: {args.m}\n")
        f.write(f"imbalance: {args.imbalance}\n")
        f.write(f"kahip_mode: {args.kahip_mode}\n")
        f.write(f"layers: {args.layers}\n")
        f.write(f"nodes: {args.nodes}\n")
        f.write(f"epochs: {args.epochs}\n")
        f.write(f"batch_size: {args.batch_size}\n")
        f.write(f"lr: {args.lr}\n")
        f.write(f"seed: {args.seed}\n")
        f.write(f"final_train_acc: {history['train_acc'][-1]:.4f}\n")
        f.write(f"final_val_acc: {history['val_acc'][-1]:.4f}\n")
        f.write(f"bin_min: {bin_min}\n")
        f.write(f"bin_max: {bin_max}\n")
        f.write(f"bin_mean: {bin_mean:.2f}\n")
        f.write(f"bin_median: {bin_median}\n")
        f.write(f"non_empty_bins: {non_empty_bins}\n")
        
    print(f"Index saved to {model_path}, {index_file_path}, and {config_path}")

if __name__ == "__main__":
    main()

