import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import kahip
import time
import pickle
import os
import subprocess
import sys
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors

# Local imports
from data_parser import get_dataset, build_parser, parse_cpp_output, save_knn_graph, load_knn_graph, get_unique_filename
from models import MLPClassifier
from graph_utils import build_kahip_graph_no_csr

def main():
    args = build_parser()
    
    # Set seeds
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # 1. Load Data
    print(f"Loading dataset from {args.dataset}...")
    X_train_np = get_dataset(args.type, args.dataset)
    n_samples, n_features = X_train_np.shape
    print(f"Data loaded: {n_samples} vectors of dimension {n_features}")

    # 2. Build or Load k-NN Graph
    dataset_name = os.path.splitext(os.path.basename(args.dataset))[0]
    
    if args.graph_method == "cpp_subprocess":
        method_str = f"cpp_{args.cpp_algo}"
    elif args.graph_method == "cpp_file":
        method_str = "cpp_file"
    else:
        method_str = "sklearn"
        
    graph_cache_path = os.path.join("cache", "graphs", f"knn_{dataset_name}_{method_str}_k{args.knn}.npy")
    
    indices = load_knn_graph(graph_cache_path)
    
    if indices is None:
        print(f"Building k-NN graph (k={args.knn}) using {args.graph_method}...")
        start_time = time.time()
        
        if args.graph_method == "sklearn":
            # We need k+1 because the first neighbor of a point in the training set is itself (dist=0)
            nbrs = NearestNeighbors(n_neighbors=args.knn + 1, algorithm='brute', metric='euclidean', n_jobs=-1)
            nbrs.fit(X_train_np)
            _, raw_indices = nbrs.kneighbors(X_train_np)
            # Remove the first column (self-loop)
            indices = raw_indices[:, 1:]
            
        elif args.graph_method == "cpp_file":
            if not args.graph_file:
                print("Error: --graph_file is required when graph_method is 'cpp_file'")
                sys.exit(1)
            # Expecting file to contain k+1 neighbors if generated by our C++ tool on train set
            # If the file was strictly generated as a graph (no self loops), adjust k accordingly.
            # Assuming standard output:
            raw_indices = parse_cpp_output(args.graph_file, n_samples, args.knn + 1)
            indices = raw_indices[:, 1:]
            
        elif args.graph_method == "cpp_subprocess":
            # Use absolute path to avoid C++ filesystem error on empty parent path
            temp_output = os.path.abspath("temp_knn_graph.txt")
            
            # Request k+1 neighbors to account for self-loops
            k_req = args.knn + 1
            
            # Pass all required arguments to avoid interactive prompts from C++
            cmd = [
                args.cpp_bin,
                "-algo", args.cpp_algo,
                "-d", args.dataset,
                "-q", args.dataset,
                "-o", temp_output,
                "-type", args.type,
                "-N", str(k_req),
                "-metric", "l2",       # Explicitly set metric
                "-range", "false",     # Disable range search for graph construction
                "-R", "0.0"
            ]
            print(f"Running C++ subprocess: {' '.join(cmd)}")
            try:
                subprocess.run(cmd, check=True)
                # Parse k+1, then remove self-loops
                raw_indices = parse_cpp_output(temp_output, n_samples, k_req)
                indices = raw_indices[:, 1:] 
                
                if os.path.exists(temp_output):
                    os.remove(temp_output)
            except subprocess.CalledProcessError as e:
                print(f"Error running C++ executable: {e}")
                sys.exit(1)
            except FileNotFoundError:
                print(f"Error: C++ executable not found at {args.cpp_bin}")
                sys.exit(1)

        print(f"k-NN graph constructed in {time.time() - start_time:.2f}s")
        save_knn_graph(indices, graph_cache_path)

    # 3. Prepare Graph for KaHIP
    xadj, adjncy, adjcwgt, vwgt = build_kahip_graph_no_csr(indices, args.knn)

    # 4. KaHIP Partitioning
    print(f"Running KaHIP partitioning (m={args.m})...")
    start_time = time.time()
    
    # Pass arguments positionally. The kahip binding does not support keyword arguments.
    # Signature: (vwgt, xadj, adjcwgt, adjncy, k, imbalance, suppress_output, seed, mode)
    edgecut, blocks = kahip.kaffpa(
        vwgt, xadj, adjcwgt, adjncy,
        args.m,
        args.imbalance,
        True,
        args.seed,
        args.kahip_mode
    )
    
    print(f"Partitioning completed in {time.time() - start_time:.2f}s. Edge cut: {edgecut}")

    # --- PLOT: Partition Balance ---
    fig_dir = os.path.join(os.path.dirname(__file__), "fig")
    os.makedirs(fig_dir, exist_ok=True)
    
    unique, counts = np.unique(blocks, return_counts=True)
    plt.figure(figsize=(10, 6))
    plt.bar(unique, counts, color='skyblue', edgecolor='black')
    plt.xlabel('Partition ID')
    plt.ylabel('Number of Points')
    plt.title(f'KaHIP Partition Balance (m={args.m}, imbalance={args.imbalance})')
    plt.grid(axis='y', alpha=0.75)
    
    # Unique filename with params
    base_plot_name = f"partition_balance_{dataset_name}_m{args.m}_imb{args.imbalance}_mode{args.kahip_mode}_seed{args.seed}.png"
    plot_path = get_unique_filename(os.path.join(fig_dir, base_plot_name))
    
    plt.savefig(plot_path)
    plt.close()
    print(f"Saved partition balance plot to {plot_path}")
    # -------------------------------

    labels = torch.tensor(blocks, dtype=torch.long).to(device)
    X_train = torch.from_numpy(X_train_np).to(device)

    # 5. Train Classifier
    print("Training Neural Classifier...")
    hidden_units = [args.nodes] * (max(1, args.layers - 1))
    
    model = MLPClassifier(
        d_in=n_features, 
        n_out=args.m, 
        hidden_units=hidden_units,
        activation='relu',
        dropout=0.1
    ).to(device)
    
    optimizer = optim.Adam(model.parameters(), lr=args.lr)
    criterion = nn.CrossEntropyLoss()
    
    dataset = TensorDataset(X_train, labels)
    loader = DataLoader(dataset, batch_size=args.batch_size, shuffle=True)
    
    model.train()
    start_time = time.time()
    epoch_losses = [] # Store losses for plotting

    for epoch in range(args.epochs):
        total_loss = 0
        for batch_x, batch_y in loader:
            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        
        avg_loss = total_loss / len(loader)
        epoch_losses.append(avg_loss)
        print(f"Epoch {epoch+1}/{args.epochs}, Loss: {avg_loss:.4f}")
    
    print(f"Training completed in {time.time() - start_time:.2f}s")

    # --- PLOT: Learning Curve ---
    plt.figure(figsize=(10, 6))
    plt.plot(range(1, args.epochs + 1), epoch_losses, marker='o', linestyle='-', color='b')
    plt.xlabel('Epoch')
    plt.ylabel('Cross Entropy Loss')
    plt.title(f'Training Loss (Layers={args.layers}, Nodes={args.nodes}, LR={args.lr})')
    plt.grid(True)
    
    # Unique filename with params
    base_loss_name = f"training_loss_{dataset_name}_L{args.layers}_N{args.nodes}_E{args.epochs}_B{args.batch_size}_LR{args.lr}_seed{args.seed}.png"
    plot_path = get_unique_filename(os.path.join(fig_dir, base_loss_name))
    
    plt.savefig(plot_path)
    plt.close()
    print(f"Saved training loss plot to {plot_path}")
    # ----------------------------

    # 6. Save Index
    # Ensure directory exists for index path
    index_dir = os.path.dirname(args.index_path)
    if index_dir:
        os.makedirs(index_dir, exist_ok=True)

    model_path = f"{args.index_path}_model.pth"
    torch.save({
        "model_state": model.state_dict(),
        "config": {
            "d_in": n_features,
            "n_out": args.m,
            "hidden_units": hidden_units,
            "activation": 'relu',
            "dropout": 0.1
        }
    }, model_path)
    
    inverted_file = {}
    blocks_np = np.array(blocks)
    for i in range(args.m):
        idxs = np.where(blocks_np == i)[0].tolist()
        inverted_file[i] = idxs
        
    index_file_path = f"{args.index_path}_index.pkl"
    with open(index_file_path, "wb") as f:
        pickle.dump(inverted_file, f)
        
    print(f"Index saved to {model_path} and {index_file_path}")

if __name__ == "__main__":
    main()

